# Config file for automatic testing at travis-ci.org

language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO="2.2"
  - DJANGO="3.2"

fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox tox-travis

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e TOXENV
